// Generated by gencpp from file kri_2021/KRSBI_BolaKoordinat.msg
// DO NOT EDIT!


#ifndef KRI_2021_MESSAGE_KRSBI_BOLAKOORDINAT_H
#define KRI_2021_MESSAGE_KRSBI_BOLAKOORDINAT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace kri_2021
{
template <class ContainerAllocator>
struct KRSBI_BolaKoordinat_
{
  typedef KRSBI_BolaKoordinat_<ContainerAllocator> Type;

  KRSBI_BolaKoordinat_()
    : x_bola(0.0)
    , y_bola(0.0)
    , z_bola(0.0)
    , x_pixel(0)
    , y_pixel(0)
    , radius(0)  {
    }
  KRSBI_BolaKoordinat_(const ContainerAllocator& _alloc)
    : x_bola(0.0)
    , y_bola(0.0)
    , z_bola(0.0)
    , x_pixel(0)
    , y_pixel(0)
    , radius(0)  {
  (void)_alloc;
    }



   typedef float _x_bola_type;
  _x_bola_type x_bola;

   typedef float _y_bola_type;
  _y_bola_type y_bola;

   typedef float _z_bola_type;
  _z_bola_type z_bola;

   typedef int16_t _x_pixel_type;
  _x_pixel_type x_pixel;

   typedef int16_t _y_pixel_type;
  _y_pixel_type y_pixel;

   typedef int16_t _radius_type;
  _radius_type radius;





  typedef boost::shared_ptr< ::kri_2021::KRSBI_BolaKoordinat_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::kri_2021::KRSBI_BolaKoordinat_<ContainerAllocator> const> ConstPtr;

}; // struct KRSBI_BolaKoordinat_

typedef ::kri_2021::KRSBI_BolaKoordinat_<std::allocator<void> > KRSBI_BolaKoordinat;

typedef boost::shared_ptr< ::kri_2021::KRSBI_BolaKoordinat > KRSBI_BolaKoordinatPtr;
typedef boost::shared_ptr< ::kri_2021::KRSBI_BolaKoordinat const> KRSBI_BolaKoordinatConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::kri_2021::KRSBI_BolaKoordinat_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::kri_2021::KRSBI_BolaKoordinat_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace kri_2021

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'kri_2021': ['/home/robotis/RobotisSoccer/src/kri_2021/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::kri_2021::KRSBI_BolaKoordinat_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kri_2021::KRSBI_BolaKoordinat_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kri_2021::KRSBI_BolaKoordinat_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kri_2021::KRSBI_BolaKoordinat_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kri_2021::KRSBI_BolaKoordinat_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kri_2021::KRSBI_BolaKoordinat_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::kri_2021::KRSBI_BolaKoordinat_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6c819dfe572dd654cecc1d700d834ad7";
  }

  static const char* value(const ::kri_2021::KRSBI_BolaKoordinat_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6c819dfe572dd654ULL;
  static const uint64_t static_value2 = 0xcecc1d700d834ad7ULL;
};

template<class ContainerAllocator>
struct DataType< ::kri_2021::KRSBI_BolaKoordinat_<ContainerAllocator> >
{
  static const char* value()
  {
    return "kri_2021/KRSBI_BolaKoordinat";
  }

  static const char* value(const ::kri_2021::KRSBI_BolaKoordinat_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::kri_2021::KRSBI_BolaKoordinat_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 x_bola\n\
float32 y_bola\n\
float32 z_bola\n\
int16 x_pixel\n\
int16 y_pixel\n\
int16 radius\n\
";
  }

  static const char* value(const ::kri_2021::KRSBI_BolaKoordinat_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::kri_2021::KRSBI_BolaKoordinat_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x_bola);
      stream.next(m.y_bola);
      stream.next(m.z_bola);
      stream.next(m.x_pixel);
      stream.next(m.y_pixel);
      stream.next(m.radius);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct KRSBI_BolaKoordinat_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::kri_2021::KRSBI_BolaKoordinat_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::kri_2021::KRSBI_BolaKoordinat_<ContainerAllocator>& v)
  {
    s << indent << "x_bola: ";
    Printer<float>::stream(s, indent + "  ", v.x_bola);
    s << indent << "y_bola: ";
    Printer<float>::stream(s, indent + "  ", v.y_bola);
    s << indent << "z_bola: ";
    Printer<float>::stream(s, indent + "  ", v.z_bola);
    s << indent << "x_pixel: ";
    Printer<int16_t>::stream(s, indent + "  ", v.x_pixel);
    s << indent << "y_pixel: ";
    Printer<int16_t>::stream(s, indent + "  ", v.y_pixel);
    s << indent << "radius: ";
    Printer<int16_t>::stream(s, indent + "  ", v.radius);
  }
};

} // namespace message_operations
} // namespace ros

#endif // KRI_2021_MESSAGE_KRSBI_BOLAKOORDINAT_H
