# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from kri_2021/BolaKoordinat.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class BolaKoordinat(genpy.Message):
  _md5sum = "6c819dfe572dd654cecc1d700d834ad7"
  _type = "kri_2021/BolaKoordinat"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """float32 x_bola
float32 y_bola
float32 z_bola
int16 x_pixel
int16 y_pixel
int16 radius
"""
  __slots__ = ['x_bola','y_bola','z_bola','x_pixel','y_pixel','radius']
  _slot_types = ['float32','float32','float32','int16','int16','int16']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       x_bola,y_bola,z_bola,x_pixel,y_pixel,radius

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(BolaKoordinat, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.x_bola is None:
        self.x_bola = 0.
      if self.y_bola is None:
        self.y_bola = 0.
      if self.z_bola is None:
        self.z_bola = 0.
      if self.x_pixel is None:
        self.x_pixel = 0
      if self.y_pixel is None:
        self.y_pixel = 0
      if self.radius is None:
        self.radius = 0
    else:
      self.x_bola = 0.
      self.y_bola = 0.
      self.z_bola = 0.
      self.x_pixel = 0
      self.y_pixel = 0
      self.radius = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3f3h().pack(_x.x_bola, _x.y_bola, _x.z_bola, _x.x_pixel, _x.y_pixel, _x.radius))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 18
      (_x.x_bola, _x.y_bola, _x.z_bola, _x.x_pixel, _x.y_pixel, _x.radius,) = _get_struct_3f3h().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3f3h().pack(_x.x_bola, _x.y_bola, _x.z_bola, _x.x_pixel, _x.y_pixel, _x.radius))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 18
      (_x.x_bola, _x.y_bola, _x.z_bola, _x.x_pixel, _x.y_pixel, _x.radius,) = _get_struct_3f3h().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3f3h = None
def _get_struct_3f3h():
    global _struct_3f3h
    if _struct_3f3h is None:
        _struct_3f3h = struct.Struct("<3f3h")
    return _struct_3f3h
